# Schema for configuration files of the Facebook Posts module.

facebook_posts.settings:
  type: config_object
  mapping:
    app_id:
      type: string
    app_secret:
      type: string
    limit:
      type: integer
      label: The maximum number of posts to keep.
    page_id:
      type: integer
      label: The numerical ID of the source page.
